# Generated by Django 3.0 on 2021-03-14 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Registration',
            fields=[
                ('academic_year', models.CharField(choices=[('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22')], default='', max_length=20)),
                ('join_date', models.DateField(blank=True, default=datetime.datetime(2021, 3, 14, 0, 3, 20, 351830))),
                ('sid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('admission_num', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=8)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='', max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A-'), ('B+', 'B-'), ('O+', 'O-'), ('AB+', 'AB-')], default='', max_length=20)),
                ('category', models.CharField(choices=[('General', 'General'), ('MCB', 'MCB'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('Other', 'Other')], default='', max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('Cast', models.CharField(choices=[('Hindus', 'Hindus'), ('Muslims', 'Muslims'), ('Christians', 'Christians'), ('Sikhs', 'Sikhs'), ('Jains', 'Jains'), ('Other', 'Other')], default='', max_length=50)),
                ('aadhar', models.CharField(max_length=12)),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=12)),
                ('photo', models.ImageField(default='', upload_to='StudentPhotos/')),
                ('father_name', models.CharField(max_length=100)),
                ('father_mobile', models.CharField(max_length=12)),
                ('father_job', models.CharField(max_length=100)),
                ('father_aadhar', models.CharField(max_length=12)),
                ('college', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('college_address', models.TextField()),
                ('course_name', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('course_type', models.CharField(choices=[('fashion', 'fashion'), ('graphics', 'graphics'), ('fineart', 'fineart'), ('textile', 'textile'), ('jwellery', 'jwellery'), ('others', 'others')], default='', max_length=200)),
                ('status', models.CharField(default='', max_length=100)),
                ('last_login', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default=models.CharField(max_length=30, primary_key=True, serialize=False), max_length=100)),
                ('cpassword', models.CharField(default=models.CharField(default=models.CharField(max_length=30, primary_key=True, serialize=False), max_length=100), max_length=100)),
            ],
        ),
    ]
