# Generated by Django 3.0 on 2021-03-14 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0002_student_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O-', 'O-'), ('O+', 'O+'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 14, 0, 15, 14, 155298)),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='status',
            field=models.CharField(default='Panding', max_length=100),
        ),
    ]
