# Generated by Django 3.0 on 2021-03-14 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0003_auto_20210314_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='cpassword',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 14, 2, 13, 43, 263109)),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
