# Generated by Django 3.0 on 2021-03-16 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0004_auto_20210314_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='cpassword',
            field=models.CharField(default='b', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 15, 23, 10, 32, 736999)),
        ),
    ]
