# Generated by Django 3.0 on 2021-03-19 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0005_auto_20210315_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Inquiry',
            fields=[
                ('inquiry_num', models.AutoField(primary_key=True, serialize=False)),
                ('inquiry_date', models.DateField(max_length=8)),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=8)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='', max_length=200)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('edu_que', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('fashion', 'fashion'), ('graphics', 'graphics'), ('fineart', 'fineart'), ('textile', 'textile'), ('jwellery', 'jwellery'), ('Art & Cart', 'Art & Cart'), ('PhotoShop', 'PhotoShop'), ('Corel Drew', 'Corel Drew'), ('Illustrator', 'Illustrator'), ('Motifs Design', 'Motifs Design')], default='', max_length=200)),
                ('reference', models.CharField(choices=[('Social Media', 'Social Media'), ('Google', 'Google'), ('News Paper', 'News Paper'), ('Others', 'Others')], default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 18, 23, 56, 54, 622669)),
        ),
    ]
