# Generated by Django 3.0 on 2021-03-19 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0006_auto_20210318_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_inquiry',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='cpassword',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 19, 2, 29, 22, 313539)),
        ),
    ]
