# Generated by Django 3.0 on 2021-03-22 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0008_auto_20210321_2013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_User',
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 21, 22, 20, 44, 944016)),
        ),
    ]
