# Generated by Django 3.0 on 2021-03-23 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0009_auto_20210321_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='institute_Detaile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_name', models.CharField(max_length=100)),
                ('ins_id', models.CharField(max_length=100)),
                ('ins_address', models.TextField()),
                ('ins_fb', models.URLField(blank=True)),
                ('ins_insta', models.URLField(blank=True)),
                ('ins_google', models.URLField(blank=True)),
                ('ins_phone', models.CharField(max_length=12)),
                ('ins_email', models.CharField(max_length=100)),
                ('ins_web', models.URLField(blank=True)),
                ('logo', models.FileField(default='', upload_to='InstituteLogo/')),
            ],
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 22, 19, 40, 20, 222617)),
        ),
    ]
