# Generated by Django 3.0 on 2021-03-24 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0010_auto_20210322_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_place', models.CharField(default='', max_length=100)),
                ('event_date', models.DateField(max_length=8)),
                ('event_time', models.TimeField()),
                ('event_status', models.CharField(default='active', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 23, 18, 59, 40, 878734)),
        ),
    ]
