# Generated by Django 3.0 on 2021-03-26 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0011_auto_20210323_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration',
            name='final_fees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student_registration',
            name='remaining_fees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 25, 22, 22, 17, 643690)),
        ),
    ]
