# Generated by Django 3.0 on 2021-03-26 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0013_auto_20210325_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfees',
            name='sid',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 26, 0, 48, 41, 265441)),
        ),
    ]
