# Generated by Django 3.0 on 2021-03-27 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0015_auto_20210326_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfees',
            name='Student',
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 27, 3, 54, 5, 242344)),
        ),
    ]
