# Generated by Django 3.0 on 2021-03-30 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0016_auto_20210327_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_for', models.CharField(choices=[('Fashion', 'Fashion'), ('Graphics', 'Graphics'), ('FineArt', 'FineArt'), ('Textile', 'Textile'), ('Jwellery', 'Jwellery'), ('All', 'All')], default='all', max_length=200)),
                ('notice_sub', models.CharField(max_length=100)),
                ('notice_date', models.DateField(max_length=8)),
                ('notice_desc', models.TextField()),
                ('notice_file', models.FileField(default='', upload_to='NoticeFiles/')),
                ('notice_status', models.CharField(default='active', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 29, 19, 51, 54, 695901)),
        ),
    ]
