# Generated by Django 3.0 on 2021-03-30 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0017_auto_20210329_1951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notice',
            new_name='Notice_Registration',
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 29, 19, 55, 7, 937690)),
        ),
    ]
