# Generated by Django 3.0 on 2021-03-31 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0019_auto_20210330_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 30, 19, 24, 46, 964470)),
        ),
        migrations.AlterField(
            model_name='submitions_registration',
            name='submitions_file',
            field=models.FileField(default='', upload_to='SubmitionsFiles/'),
        ),
    ]
