# Generated by Django 3.0 on 2021-03-31 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0020_auto_20210330_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('from_date', models.DateField(max_length=8)),
                ('to_date', models.DateField(max_length=8)),
                ('Leave_catagory', models.CharField(choices=[('Sick_Leave', 'Sick_Leave'), ('Extended_Sick', 'Extended_Sick'), ('Emergency_Leave', 'Emergency_Leave'), ('Long_Leave', 'Long_Leave'), ('Others', 'Others')], default='', max_length=200)),
                ('leave_reason', models.CharField(max_length=100)),
                ('leave_day', models.CharField(max_length=100)),
                ('status', models.CharField(default='Panding_Request', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 31, 0, 34, 8, 807978)),
        ),
    ]
