# Generated by Django 3.0 on 2021-03-31 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0022_auto_20210331_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_leave',
            old_name='leave_day',
            new_name='Leave_day',
        ),
        migrations.RenameField(
            model_name='student_leave',
            old_name='leave_reason',
            new_name='Leave_reason',
        ),
        migrations.AlterField(
            model_name='student_leave',
            name='Leave_catagory',
            field=models.CharField(choices=[('Sick_Leave', 'Sick Leave ( 1 to 2 days )'), ('Extended_Sick', 'Extended Sick Leave'), ('Emergency_Leave', 'Emergency Leave'), ('Long_Leave', 'Long Leave'), ('Others', 'Others')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 31, 1, 5, 44, 205079)),
        ),
    ]
