# Generated by Django 3.0 on 2021-04-01 10:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0023_auto_20210331_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 31, 23, 36, 3, 60057)),
        ),
        migrations.CreateModel(
            name='Student_Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_msg', models.TextField()),
                ('suggestion_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Student_Registration')),
            ],
        ),
    ]
