# Generated by Django 3.0 on 2021-04-02 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0024_auto_20210331_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_for', models.CharField(choices=[('Fashion', 'Fashion'), ('Graphics', 'Graphics'), ('FineArt', 'FineArt'), ('Textile', 'Textile'), ('Jwellery', 'Jwellery'), ('All', 'All')], default='all', max_length=200)),
                ('book_title', models.CharField(max_length=100)),
                ('book_link', models.URLField(blank=True)),
                ('book_photo', models.FileField(default='', upload_to='ELibraryBookPhoto/')),
                ('book_pdf', models.FileField(default='', upload_to='ELibraryBookPDF/')),
            ],
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 2, 0, 59, 51, 468384)),
        ),
    ]
