# Generated by Django 3.0 on 2021-04-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0026_auto_20210402_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='join_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentfees',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Student_Suggestion',
        ),
    ]
