# Generated by Django 3.0 on 2021-04-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0027_auto_20210404_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=100)),
                ('Student_Suggestion', models.TextField()),
                ('Suggestion_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
