# Generated by Django 3.0 on 2021-04-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0028_student_suggestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_suggestion',
            old_name='Suggestion_date',
            new_name='suggestion_date',
        ),
    ]
