# Generated by Django 3.0 on 2021-04-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0029_auto_20210404_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='last_login',
            field=models.DateField(auto_now=True),
        ),
    ]
