# Generated by Django 3.0 on 2021-04-04 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0033_auto_20210404_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
