# Generated by Django 3.0 on 2021-04-05 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0038_auto_20210404_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_suggestion',
            name='sid',
        ),
        migrations.AddField(
            model_name='student_suggestion',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Student_Registration'),
        ),
    ]
