# Generated by Django 3.0 on 2021-04-07 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0041_auto_20210407_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Admin_Registration'),
        ),
    ]
