# Generated by Django 3.0 on 2021-04-07 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0042_student_registration_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='elibrary',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Admin_Registration'),
        ),
        migrations.AddField(
            model_name='event_registration',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Admin_Registration'),
        ),
        migrations.AddField(
            model_name='student_inquiry',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Admin_Registration'),
        ),
        migrations.AddField(
            model_name='studentfees',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Admin_Registration'),
        ),
        migrations.AddField(
            model_name='submitions_registration',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Admin_Registration'),
        ),
    ]
