# Generated by Django 3.0 on 2021-04-07 15:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0044_notice_registration_admin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_Registration',
            fields=[
                ('faculty_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('joing_date', models.DateField(max_length=8)),
                ('department_catagory', models.CharField(choices=[('Teaching', 'Teaching'), ('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Non Teaching Staff', 'Non Teaching Staff'), ('Administartor', 'Administartor')], default='', max_length=200)),
                ('designation_catagory', models.CharField(choices=[('Primary Teacher', 'Primary Teacher'), ('Admin', 'Admin'), ('Gurdiance', 'Gurdiance'), ('Non Teaching Staff', 'Non Teaching Staff'), ('Class Teacher', 'Class Teacher')], default='', max_length=200)),
                ('qulification', models.CharField(max_length=80)),
                ('total_Experiance', models.CharField(max_length=80)),
                ('first_name', models.CharField(max_length=50)),
                ('middel_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(max_length=8)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='', max_length=10)),
                ('aadhar', models.CharField(max_length=12)),
                ('salary', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('photo', models.ImageField(default='', upload_to='FacultyPhotos/')),
                ('holder_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=50)),
                ('online_payment_catagory', models.CharField(choices=[('Upi', 'Upi'), ('Phonepe', 'Phonepe'), ('paytm', 'paytm'), ('MobiKwik', 'MobiKwik'), ('Amazon', 'Amazon')], default='', max_length=200)),
                ('status', models.CharField(default='Panding', max_length=100)),
                ('last_login', models.DateField(default=django.utils.timezone.now)),
                ('password', models.CharField(default='', max_length=100)),
                ('cpassword', models.CharField(default='', max_length=100)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Admin_Registration')),
            ],
        ),
    ]
