# Generated by Django 3.0 on 2021-04-08 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0045_faculty_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_inquiry',
            name='faculty_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Faculty_Registration'),
        ),
    ]
