# Generated by Django 3.0 on 2021-04-08 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0046_student_inquiry_faculty_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='elibrary',
            name='faculty_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Faculty_Registration'),
        ),
        migrations.AddField(
            model_name='submitions_registration',
            name='faculty_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Faculty_Registration'),
        ),
    ]
