# Generated by Django 3.0 on 2021-04-09 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0047_auto_20210408_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_Name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('from_date', models.DateField(max_length=8)),
                ('to_date', models.DateField(max_length=8)),
                ('Leave_catagory', models.CharField(choices=[('Sick_Leave', 'Sick Leave ( 1 to 2 days )'), ('Extended_Sick', 'Extended Sick Leave'), ('Emergency_Leave', 'Emergency Leave'), ('Long_Leave', 'Long Leave'), ('Others', 'Others')], default='', max_length=200)),
                ('Leave_reason', models.CharField(max_length=100)),
                ('Leave_day', models.CharField(max_length=100)),
                ('status', models.CharField(default='Panding_Request', max_length=100)),
                ('faculty_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Faculty_Registration')),
            ],
        ),
    ]
