# Generated by Django 3.0 on 2021-04-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0050_auto_20210410_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_Salary',
            fields=[
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='', max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('payment_date', models.DateField(max_length=8)),
                ('payment_type', models.CharField(max_length=100)),
                ('from_date', models.DateField(default='', max_length=8)),
                ('to_date', models.DateField(default='', max_length=8)),
                ('recipt_no', models.AutoField(primary_key=True, serialize=False)),
                ('salary_invoice', models.FileField(default='', upload_to='SalaryInvoice/')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Admin_Registration')),
                ('faculty_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Faculty_Registration')),
            ],
        ),
    ]
