# Generated by Django 3.0 on 2021-04-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0051_faculty_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_salary',
            name='year',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2022', '2022')], default='', max_length=200),
        ),
    ]
