# Generated by Django 3.0 on 2021-04-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0052_faculty_salary_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_registration',
            name='description',
        ),
        migrations.RemoveField(
            model_name='faculty_registration',
            name='designation_catagory',
        ),
        migrations.RemoveField(
            model_name='faculty_registration',
            name='online_payment_catagory',
        ),
        migrations.AddField(
            model_name='faculty_registration',
            name='Cast',
            field=models.CharField(choices=[('Hindus', 'Hindus'), ('Muslims', 'Muslims'), ('Christians', 'Christians'), ('Sikhs', 'Sikhs'), ('Jains', 'Jains'), ('Other', 'Other')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='faculty_registration',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O-', 'O-'), ('O+', 'O+'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='faculty_registration',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('MCB', 'MCB'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('Other', 'Other')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='faculty_registration',
            name='ifsc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty_registration',
            name='nationality',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty_registration',
            name='account_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty_registration',
            name='bank_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty_registration',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty_registration',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty_registration',
            name='department_catagory',
            field=models.CharField(choices=[('fashion', 'fashion'), ('graphics', 'graphics'), ('fineart', 'fineart'), ('textile', 'textile'), ('jwellery', 'jwellery'), ('others', 'others')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='faculty_registration',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty_registration',
            name='holder_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty_registration',
            name='mobile',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='faculty_registration',
            name='pin',
            field=models.CharField(default='', max_length=10),
        ),
    ]
