# Generated by Django 3.1.2 on 2021-04-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0053_auto_20210414_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_registration',
            name='country',
        ),
    ]
