# Generated by Django 3.0 on 2021-04-19 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0054_remove_faculty_registration_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_registration',
            name='event_status',
        ),
        migrations.RemoveField(
            model_name='student_inquiry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student_schedule',
            name='status',
        ),
        migrations.RemoveField(
            model_name='submitions_registration',
            name='notice_status',
        ),
        migrations.CreateModel(
            name='Student_Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_date', models.DateField(default='', max_length=8)),
                ('batch', models.CharField(max_length=100)),
                ('late_arrival', models.CharField(max_length=100)),
                ('ap', models.CharField(max_length=100)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Admin_Registration')),
                ('faculty_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Faculty_Registration')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Student_Registration')),
            ],
        ),
    ]
