# Generated by Django 3.0 on 2021-04-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0056_student_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_registration',
            name='status',
            field=models.CharField(default='activated', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty_registration',
            name='status',
            field=models.CharField(default='activated', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='status',
            field=models.CharField(default='activated', max_length=100),
        ),
    ]
