# Generated by Django 3.0 on 2021-05-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0058_auto_20210427_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_certificate',
            name='certificate_pdf',
            field=models.FileField(default='', upload_to='StudenCertificate/'),
        ),
    ]
