# Generated by Django 3.0 on 2021-06-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0059_student_certificate_certificate_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_attendence',
            name='ap',
            field=models.CharField(choices=[('A', 'Absent'), ('P', 'Present')], default='A', max_length=1),
        ),
    ]
